project:
  type: website

website:
  title: "aznale"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - goalsMindtable.qmd
      - labsQuartoTool.qmd
      - penguins.ipynb
      - react.qmd
      - resources.qmd
      - rest.qmd
      - spring.qmd
      - Projects/svg.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true





