---
title: "Goals Mindtable"
---

## Mindtable
### 3/4/23 -> 7/4/23


| Mins | M                                     | T                                         | W                               | T                               | F   |
| :--: | ------------------------------------- | ----------------------------------------- | ------------------------------- | ------------------------------- | --- |
|  90  | **Quarto**<br>Create Mindtable        | **REST**<br> Update Book                  | **Quarto**<br>Learn             | **Rest**<br>CRUD Borrow         |     |
|  90  | **Quarto**<br>Learn Quarto            | **REST**<br> Update User                  | ~~**Git**̣~~**Quarto**<br>Learn                | **Rest**<br>CRUD Borrow         |     |
|  60  | **Spring Boot** Udemy<br>Dependencies | ~~**Spring Boot** Udemy<br>Dependencies~~ | **Git**<br>Learn and document   | **Spring Boot**<br> Udemy       |     |
|  60  | **Spring Boot** Udemy<br>Dependencies | ~~**Spring Boot** Udemy<br>Dependencies~~ | **Lecture**<br>Thinking in java | **Lecture**<br>Thinking in java |     |

#### Summary of goals
**Git**: Learn Git, deepen and understand it.

:::{.border}
(...)
:::
---

**Quarto**: Learn Quarto, to document all learnings.

:::{.border}
- [x] Create Mindtable
- [x] Markdown Basics, Figures, Tables, Videos, Callouts
:::
---

**Spring fw**: Learn Spring & Spring Boot.

:::{.border}
(...)
:::
---

**Rest**: Do the class exercises.

:::{.border}
- [x] Update Book
- [x] Update User
:::
--- 

::: {.callout-tip title="To Learn"}
## To Learn
[Revealjs](https://quarto.org/docs/presentations/revealjs/) tool for presentations & [Jupyter notebook](https://quarto.org/docs/authoring/notebook-embed.html) for sharing computational documents.
:::

::: {.callout-important title="ToDo"}
## ToDo
- Jupyter Anotations
- Code Annotation
- Revealjs
- Article Layout `R`
:::

